# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          repository: lxc/lxc-ci
          ref: bc78ee5e27ade74f31162f66f370d89ec2567667
          sparse-checkout: |
            images/debian.yaml
          sparse-checkout-cone-mode: false
          path: lxc-ci
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y e2fsprogs qemu-utils debootstrap guestfs-tools oras yq
      - run: |
          cat lxc-ci/images/debian.yaml | yq -y '
            .image = {
              "distribution": "debian",
              "name": "debian-trixie-x86_64",
              "release": "trixie",
              "description": "Debian",
              "architecture": "x86_64"
            } > debian.yaml
          EOF
      - run: |
          nix-shell -p distrobuilder --command 'ln -s $(which distrobuilder) distrobuilder'
          sudo ./distrobuilder build-incus ./debian.yaml debian-output --vm
          ls -lR debian-output
          virt-builder --get-kernel debian-output/disk.qcow2
          ls -lR debian-output
